version: "3"
services:
	app:
		container_name: nginx_proxy # reserved name for cron
		image: 'docker.io/jc21/nginx-proxy-manager:latest'
		restart: unless-stopped
		ports:
			# These ports are in format <host-port>:<container-port>
			- '80:80' # Public HTTP Port
			- '443:443' # Public HTTPS Port
			- '81:81' # Admin Web Port
			# Add any other Stream port you want to expose
			# - '21:21' # FTP
		networks:
            - nginx_proxy
		secrets:
            - mysql_user
            - mysql_password
    	environment:
			DB_MYSQL_HOST: "db"
			DB_MYSQL_PORT: 3306
			DB_MYSQL_NAME_FILE: /run/secrets/mysql_user
			DB_MYSQL_USER_FILE: /run/secrets/mysql_user
			DB_MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
			# Uncomment this if IPv6 is not enabled on your host
			# DISABLE_IPV6: 'true'
    	volumes:
			- ./nginx:/data:z
			- ./letsencrypt:/etc/letsencrypt:z
    	depends_on:
      		- db
  	db:
		container_name: nginx_proxy_db # reserved name for cron
		image: 'docker.io/jc21/mariadb-aria:latest'
		restart: unless-stopped
		networks:
            - nginx_proxy
		secrets:
            - mysql_root_password
            - mysql_user
            - mysql_password
		environment:
			MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
			MYSQL_DATABASE_FILE: /run/secrets/mysql_user
			MYSQL_USER_FILE: /run/secrets/mysql_user
			MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    	volumes:
      		- ./db:/var/lib/mysql:z
	phpmyqdmin:
        container_name: nginx_proxy_phpmyadmin
        image: docker.io/library/phpmyadmin:latest
        ports:
            - 8180:8080
            - 8143:8443
        networks:
            - nginx_proxy
        volumes:
            - ./db:/bitnami/mariadb/data:rw
		depends_on:
            - db
secrets:
    mysql_root_password:
        file: ./mysql_root_password.txt
    mysql_user:
        file: ./mysql_user.txt
    mysql_password:
        file: ./mysql_password.txt
networks:
    nginx_proxy: