version: "3"
services:
  app:
    container_name: nginx_proxy # reserved name for cron
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      - nginx-proxy
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "npm"
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./nginx:/data:z
      - ./letsencrypt:/etc/letsencrypt:z
    depends_on:
      - db
  db:
    container_name: nginx_proxy_db # reserved name for cron
    image: 'docker.io/jc21/mariadb-aria:latest'
    restart: unless-stopped
    networks:
      - nginx-proxy
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./db:/var/lib/mysql:z
  # phpmyqdmin: # not worked and with oficial image too
  #   container_name: nginx_proxy_phpmyadmin
  #   image: 'docker.io/bitnami/phpmyadmin:latest'
  #   privileged: true
  #   ports:
  #     - 8180:8080
  #     - 8143:8443
  #   networks:
  #     - nginx-proxy
  #   volumes:
  #     - ./db:/bitnami/mariadb/data:rw
  #   depends_on:
  #     - db
networks:
  nginx-proxy: